#!/usr/bin/env python3
import boto3

boto3.setup_default_session()
client = boto3.client('lambda', endpoint_url="http://localhost:4566")
response = client.list_functions()

for function in response["Functions"]:
    name = function['FunctionName']
    handler = function['Handler']
    print(name, handler)
