#!/usr/bin/env python3
import yaml
from ruamel.yaml import YAML
from ruamel.yaml.scalarstring import PreservedScalarString as pss
ryaml = YAML()

t = yaml.safe_load(open("cdk_template/template_as_generated_by_cdk.yaml"))
t.pop("Rules")
t.pop("Conditions")
t.pop("Parameters")
t["Resources"].pop("CDKMetadata")
for resource in t["Resources"].keys():
    try:
        t["Resources"][resource].pop("Metadata")
    except:
        pass
    
    type = t['Resources'][resource]['Type']
    if type=="AWS::Lambda::Function":
        handler = t['Resources'][resource]['Properties']['Handler']
        lambda_file = handler.split(".")[0]
        lambda_function = handler.split(".")[1]
        #print("        Modifying Lambda resouce "+resource)
        #t["Resources"][resource]["Properties"]["Code"] = { }
        #t["Resources"][resource]["Properties"]["Code"]["ZipFile"] = "print('placeholder code')" 
 
ryaml.dump(t, open("template.yaml", 'w'))
